version: '3.8'

services:
  nginx:
#    image: nginx:1
    image: nginx:1-alpine
    container_name: nginx
#    restart: always
    ports:
      - 80:80
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
#     - /some/content:/usr/share/nginx/html
    networks:
      - nginx
    depends_on:
      - php

  php:
#    image: php:7-fpm
    image: php:7-fpm-alpine
    container_name: php
#    ports:
#      - 9000:9000
    volumes:
      - ./code:/code
    networks:
      - nginx

networks:
  nginx:
