version: '3.7'

services:
  nginx:
    image: nginx:1.17.6
    container_name: nginx
    # restart: always
    ports:
      - 80:80
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
#     - /some/content:/usr/share/nginx/html
    links:
      - php
  php:
    image: php:7.4.0-fpm
    volumes:
      - ./code:/code
