version: '3.9'

services:
  nginx:
    image: nginx:1-alpine
    container_name: nginx
    hostname: nginx
    ports:
      - 80:80
    volumes:
      - ./code:/php/code
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/site.conf:/etc/nginx/conf.d/site.conf:ro
    networks:
      - nginx
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile-buster
    image: php-mongodb:7-fpm
    container_name: php
    hostname: php
    volumes:
      - ./code:/php/code
    networks:
      - nginx

networks:
  nginx: